export const TASK_KEYWORDS = {
  code: ['code', 'api', 'sql', 'regex', 'test', 'debug', 'developer', 'engineering', 'kubernetes', 'solidity', 'smart contract'],
  debug: ['debug', 'bug', 'error', 'troubleshoot', 'incident', 'log', 'failure'],
  review: ['review', 'audit', 'quality', 'risk', 'security', 'complexity'],
  analyze: ['analyze', 'analysis', 'report', 'evaluate', 'diagnose', 'screen', 'detect'],
  write: ['write', 'writer', 'copy', 'email', 'post', 'script', 'proposal', 'letter', 'description'],
  generate: ['generate', 'generator', 'create', 'builder'],
  rewrite: ['rewrite', 'tone', 'improve', 'optimize'],
  optimize: ['seo', 'optimize', 'keyword', 'performance', 'cost'],
  research: ['research', 'compare', 'comparison', 'competitive', 'market', 'findings', 'evidence'],
  summarize: ['summary', 'summarize', 'notes', 'pdf', 'log'],
  explain: ['explain', 'eli5', 'explainer', 'guide'],
  quiz: ['quiz', 'flashcard', 'study', 'exam', 'paper'],
  practice: ['interview', 'practice', 'dsa'],
  plan: ['plan', 'planner', 'roadmap', 'checklist', 'onboarding', 'runbook'],
  strategy: ['strategy', 'prd', 'product', 'business', 'startup', 'sales'],
  design: ['design', 'palette', 'font', 'typography', 'image', 'visual', 'game'],
  creative: ['creative', 'ideas', 'lore', 'dialogue', 'image', 'story'],
  technical: ['technical', 'architecture', 'database', 'cloud', 'ci/cd', 'etl'],
  audit: ['audit', 'review', 'score', 'risk', 'security'],
  checklist: ['checklist', 'steps', 'plan', 'runbook'],
  structure: ['structured', 'document', 'template', 'format'],
  document: ['document', 'documentation', 'report', 'proposal', 'prd'],
  automation: ['automation', 'automate', 'workflow', 'pipeline', 'cron', 'schedule'],
  data: ['data', 'dataset', 'sql', 'query', 'etl', 'model', 'analytics'],
  image: ['image', 'visual', 'photo', 'illustration', 'prompt'],
}

export const CAPABILITY_KEYWORDS = {
  toolCalling: ['tool calling', 'tools', 'api', 'automation', 'workflow'],
  fastResponses: ['fast', 'quick', 'instant', 'rapid', 'lightweight', 'direct'],
  visionSupport: ['vision', 'image', 'visual', 'photo', 'screenshot'],
  structuredOutput: ['structured', 'json', 'schema', 'format', 'report', 'template', 'yaml', 'table'],
  openSource: ['open source', 'open-source', 'github'],
  frequentlyUpdated: ['frequently updated', 'regularly updated', 'actively maintained', 'latest', 'up-to-date'],
}
